import { useState } from "react";
import { Send, Bot, User, Loader2 } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";

interface QueryInterfaceProps {
  onQuery: (query: string, response: string) => void;
}

export const QueryInterface = ({ onQuery }: QueryInterfaceProps) => {
  const [query, setQuery] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [conversation, setConversation] = useState<Array<{
    id: string;
    type: 'user' | 'bot';
    message: string;
    timestamp: Date;
  }>>([]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim() || isLoading) return;

    const userMessage = {
      id: `${Date.now()}-user`,
      type: 'user' as const,
      message: query,
      timestamp: new Date()
    };

    setConversation(prev => [...prev, userMessage]);
    setIsLoading(true);

    // Simulate AI processing
    await new Promise(resolve => setTimeout(resolve, 1500));

    // Generate a simulated response
    const responses = [
      "Based on the uploaded documents, I can help you with that. Here's what I found...",
      "I've analyzed the relevant sections from your knowledge base. The answer is...",
      "According to the training materials, this relates to...",
      "Let me provide you with information from the uploaded documents...",
      "I found several relevant passages that address your question..."
    ];

    const botResponse = responses[Math.floor(Math.random() * responses.length)] + 
      ` This is a simulated response to: "${query}". In a real implementation, this would be generated by analyzing your uploaded documents.`;

    const botMessage = {
      id: `${Date.now()}-bot`,
      type: 'bot' as const,
      message: botResponse,
      timestamp: new Date()
    };

    setConversation(prev => [...prev, botMessage]);
    onQuery(query, botResponse);
    setQuery("");
    setIsLoading(false);
  };

  const clearConversation = () => {
    setConversation([]);
  };

  return (
    <div className="grid gap-6 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Send className="h-5 w-5" />
            Test Your Bot
          </CardTitle>
          <CardDescription>
            Ask questions to test how well your bot understands the uploaded documents
          </CardDescription>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-4">
            <Textarea
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder="Ask a question about your documents..."
              className="min-h-[100px] resize-none"
              disabled={isLoading}
            />
            <div className="flex gap-2">
              <Button 
                type="submit" 
                disabled={!query.trim() || isLoading}
                className="flex-1"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                    Processing...
                  </>
                ) : (
                  <>
                    <Send className="h-4 w-4 mr-2" />
                    Ask Question
                  </>
                )}
              </Button>
              {conversation.length > 0 && (
                <Button 
                  type="button" 
                  variant="outline"
                  onClick={clearConversation}
                  disabled={isLoading}
                >
                  Clear
                </Button>
              )}
            </div>
          </form>

          <div className="mt-4 text-xs text-muted-foreground space-y-1">
            <p>• Try asking specific questions about your documents</p>
            <p>• Test edge cases and complex queries</p>
            <p>• Use the feedback system to improve responses</p>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Conversation</CardTitle>
          <CardDescription>
            Live chat interface showing queries and responses
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-4 max-h-[400px] overflow-y-auto">
            {conversation.length === 0 ? (
              <div className="text-center text-muted-foreground py-8">
                <Bot className="h-8 w-8 mx-auto mb-2 opacity-50" />
                <p>No conversation yet.</p>
                <p className="text-xs">Ask a question to get started!</p>
              </div>
            ) : (
              conversation.map((message) => (
                <div
                  key={message.id}
                  className={`flex items-start gap-3 ${
                    message.type === 'user' ? 'justify-end' : 'justify-start'
                  }`}
                >
                  {message.type === 'bot' && (
                    <div className="h-8 w-8 rounded-full bg-primary flex items-center justify-center flex-shrink-0">
                      <Bot className="h-4 w-4 text-primary-foreground" />
                    </div>
                  )}
                  
                  <div
                    className={`chat-bubble ${
                      message.type === 'user' 
                        ? 'chat-bubble-user' 
                        : 'chat-bubble-bot'
                    }`}
                  >
                    <p className="text-sm">{message.message}</p>
                    <p className="text-xs opacity-70 mt-1">
                      {message.timestamp.toLocaleTimeString()}
                    </p>
                  </div>

                  {message.type === 'user' && (
                    <div className="h-8 w-8 rounded-full bg-muted flex items-center justify-center flex-shrink-0">
                      <User className="h-4 w-4 text-muted-foreground" />
                    </div>
                  )}
                </div>
              ))
            )}
            
            {isLoading && (
              <div className="flex items-start gap-3">
                <div className="h-8 w-8 rounded-full bg-primary flex items-center justify-center flex-shrink-0">
                  <Bot className="h-4 w-4 text-primary-foreground" />
                </div>
                <div className="chat-bubble chat-bubble-bot">
                  <div className="flex items-center gap-2">
                    <Loader2 className="h-4 w-4 animate-spin" />
                    <span className="text-sm">Thinking...</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};